In [33]:
import pandas as pd

In [66]:
df = pd.read_csv("data/silver_20250322_Airline_Reviews_SentimentImageLabelsMerged.csv")
df

,RowId,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,...,sentiment_label,sentiment_score,img_resnet50_score,img_resnet50_label,img_blip_caption,img_clip_embedding,img_caption_clip_embedding,img_resnet50label_clip_embedding,img_vs_caption_similarity,img_caption_vs_resnetlabel_similarity
0,0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,https://www.airlinequality.com/wp-content/uplo...,NaN,Solo Leisure,...,positive,0.918486,5.190325,military aircraft,a man taking a picture of a plane,"tensor([[ 3.5914e-02, -2.8891e-02, 4.5510e-03...","tensor([[ 1.0825e-02, 8.4288e-03, -3.1653e-02...","tensor([[ 9.1185e-03, -1.0847e-02, 1.6327e-02...",0.251976,0.738985
1,1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,NaN,E120,Solo Leisure,...,negative,0.569241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,NaN,Embraer E120,Solo Leisure,...,neutral,0.542810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,NaN,Solo Leisure,...,negative,0.903330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,NaN,Couple Leisure,...,negative,0.902472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24349,24349,ZIPAIR,1,"""customer service is terrible""",5th July 2022,False,Bangkok to Tokyo. Iâ€™ve flown many low cost ai...,NaN,NaN,Couple Leisure,...,negative,0.842372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24350,24350,ZIPAIR,1,"""Avoid at all costs""",1st June 2022,True,Avoid at all costs. I booked flights to go f...,NaN,NaN,Solo Leisure,...,negative,0.836562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24351,24351,ZIPAIR,3,"""Will not recommend to anyone""",31st May 2022,True,Flight was leaving at 23.15 and after an hou...,NaN,NaN,Business,...,negative,0.797939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24352,24352,ZIPAIR,6,"""It was immaculately clean""",23rd May 2022,True,Zipair is JALâ€™s budget airline. They donâ€™t ha...,NaN,Dreamliner,Business,...,neutral,0.654033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24353,24353,ZIPAIR,1,"""lost all of our money with no refund""",20th May 2022,True,They lied about connection in Narita and we ...,NaN,NaN,Solo Leisure,...,negative,0.929426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Correct Overall_Rating 10 bug

In [68]:
df_20250324 = pd.read_csv("data/bronze_20250324_Airline_Reviews_withImageUrls.csv")
df_20250324

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,...,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,https://www.airlinequality.com/wp-content/uplo...,NaN,Solo Leisure,...,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,NaN,E120,Solo Leisure,...,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,NaN,Embraer E120,Solo Leisure,...,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,NaN,Solo Leisure,...,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,NaN,Couple Leisure,...,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24349,24349,ZIPAIR,1,"""customer service is terrible""",5th July 2022,False,Bangkok to Tokyo. Iâ€™ve flown many low cost ai...,NaN,NaN,Couple Leisure,...,Bangkok to Tokyo,June 2022,2.0,1.0,NaN,1.0,1.0,1.0,1.0,no
24350,24350,ZIPAIR,1,"""Avoid at all costs""",1st June 2022,True,Avoid at all costs. I booked flights to go f...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,June 2022,NaN,NaN,NaN,NaN,NaN,NaN,1.0,no
24351,24351,ZIPAIR,3,"""Will not recommend to anyone""",31st May 2022,True,Flight was leaving at 23.15 and after an hou...,NaN,NaN,Business,...,Bangkok to Tokyo,May 2022,2.0,4.0,2.0,1.0,NaN,NaN,2.0,no
24352,24352,ZIPAIR,6,"""It was immaculately clean""",23rd May 2022,True,Zipair is JALâ€™s budget airline. They donâ€™t ha...,NaN,Dreamliner,Business,...,Tokyo to Los Angeles,May 2022,3.0,4.0,3.0,1.0,2.0,5.0,5.0,yes
24353,24353,ZIPAIR,1,"""lost all of our money with no refund""",20th May 2022,True,They lied about connection in Narita and we ...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,May 2022,NaN,NaN,NaN,1.0,NaN,NaN,1.0,no

In [70]:
df_20250324.rename(columns={"Unnamed: 0": "RowId"}, inplace=True)
df_20250324

,RowId,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,...,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,https://www.airlinequality.com/wp-content/uplo...,NaN,Solo Leisure,...,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,NaN,E120,Solo Leisure,...,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,NaN,Embraer E120,Solo Leisure,...,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,NaN,Solo Leisure,...,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,NaN,Couple Leisure,...,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24349,24349,ZIPAIR,1,"""customer service is terrible""",5th July 2022,False,Bangkok to Tokyo. Iâ€™ve flown many low cost ai...,NaN,NaN,Couple Leisure,...,Bangkok to Tokyo,June 2022,2.0,1.0,NaN,1.0,1.0,1.0,1.0,no
24350,24350,ZIPAIR,1,"""Avoid at all costs""",1st June 2022,True,Avoid at all costs. I booked flights to go f...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,June 2022,NaN,NaN,NaN,NaN,NaN,NaN,1.0,no
24351,24351,ZIPAIR,3,"""Will not recommend to anyone""",31st May 2022,True,Flight was leaving at 23.15 and after an hou...,NaN,NaN,Business,...,Bangkok to Tokyo,May 2022,2.0,4.0,2.0,1.0,NaN,NaN,2.0,no
24352,24352,ZIPAIR,6,"""It was immaculately clean""",23rd May 2022,True,Zipair is JALâ€™s budget airline. They donâ€™t ha...,NaN,Dreamliner,Business,...,Tokyo to Los Angeles,May 2022,3.0,4.0,3.0,1.0,2.0,5.0,5.0,yes
24353,24353,ZIPAIR,1,"""lost all of our money with no refund""",20th May 2022,True,They lied about connection in Narita and we ...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,May 2022,NaN,NaN,NaN,1.0,NaN,NaN,1.0,no

In [72]:
right_columns_needed = ['RowId','Overall_Rating']

df_merged= pd.merge(df, df_20250324[right_columns_needed], on='RowId', how='inner', suffixes=('_left', '_right'))
df_merged

,RowId,Airline Name,Overall_Rating_left,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,...,sentiment_score,img_resnet50_score,img_resnet50_label,img_blip_caption,img_clip_embedding,img_caption_clip_embedding,img_resnet50label_clip_embedding,img_vs_caption_similarity,img_caption_vs_resnetlabel_similarity,Overall_Rating_right
0,0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,https://www.airlinequality.com/wp-content/uplo...,NaN,Solo Leisure,...,0.918486,5.190325,military aircraft,a man taking a picture of a plane,"tensor([[ 3.5914e-02, -2.8891e-02, 4.5510e-03...","tensor([[ 1.0825e-02, 8.4288e-03, -3.1653e-02...","tensor([[ 9.1185e-03, -1.0847e-02, 1.6327e-02...",0.251976,0.738985,9
1,1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,NaN,E120,Solo Leisure,...,0.569241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,NaN,Embraer E120,Solo Leisure,...,0.542810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,NaN,Solo Leisure,...,0.903330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,NaN,Couple Leisure,...,0.902472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24349,24349,ZIPAIR,1,"""customer service is terrible""",5th July 2022,False,Bangkok to Tokyo. Iâ€™ve flown many low cost ai...,NaN,NaN,Couple Leisure,...,0.842372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
24350,24350,ZIPAIR,1,"""Avoid at all costs""",1st June 2022,True,Avoid at all costs. I booked flights to go f...,NaN,NaN,Solo Leisure,...,0.836562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
24351,24351,ZIPAIR,3,"""Will not recommend to anyone""",31st May 2022,True,Flight was leaving at 23.15 and after an hou...,NaN,NaN,Business,...,0.797939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
24352,24352,ZIPAIR,6,"""It was immaculately clean""",23rd May 2022,True,Zipair is JALâ€™s budget airline. They donâ€™t ha...,NaN,Dreamliner,Business,...,0.654033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
24353,24353,ZIPAIR,1,"""lost all of our money with no refund""",20th May 2022,True,They lied about connection in Narita and we ...,NaN,NaN,Solo Leisure,...,0.929426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [76]:
df_merged.rename(columns={"Overall_Rating_right": "Overall_Rating"}, inplace=True)
df_merged.drop(columns=['Overall_Rating_left'], inplace=True)
df_corrected_overallrating10 = df_merged
df_corrected_overallrating10

,RowId,Airline Name,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,Seat Type,...,sentiment_score,img_resnet50_score,img_resnet50_label,img_blip_caption,img_clip_embedding,img_caption_clip_embedding,img_resnet50label_clip_embedding,img_vs_caption_similarity,img_caption_vs_resnetlabel_similarity,Overall_Rating
0,0,AB Aviation,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,https://www.airlinequality.com/wp-content/uplo...,NaN,Solo Leisure,Economy Class,...,0.918486,5.190325,military aircraft,a man taking a picture of a plane,"tensor([[ 3.5914e-02, -2.8891e-02, 4.5510e-03...","tensor([[ 1.0825e-02, 8.4288e-03, -3.1653e-02...","tensor([[ 9.1185e-03, -1.0847e-02, 1.6327e-02...",0.251976,0.738985,9
1,1,AB Aviation,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,NaN,E120,Solo Leisure,Economy Class,...,0.569241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2,AB Aviation,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,NaN,Embraer E120,Solo Leisure,Economy Class,...,0.542810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,3,Adria Airways,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,NaN,Solo Leisure,Economy Class,...,0.903330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,4,Adria Airways,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,NaN,Couple Leisure,Economy Class,...,0.902472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24349,24349,ZIPAIR,"""customer service is terrible""",5th July 2022,False,Bangkok to Tokyo. Iâ€™ve flown many low cost ai...,NaN,NaN,Couple Leisure,Economy Class,...,0.842372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
24350,24350,ZIPAIR,"""Avoid at all costs""",1st June 2022,True,Avoid at all costs. I booked flights to go f...,NaN,NaN,Solo Leisure,Economy Class,...,0.836562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
24351,24351,ZIPAIR,"""Will not recommend to anyone""",31st May 2022,True,Flight was leaving at 23.15 and after an hou...,NaN,NaN,Business,Economy Class,...,0.797939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
24352,24352,ZIPAIR,"""It was immaculately clean""",23rd May 2022,True,Zipair is JALâ€™s budget airline. They donâ€™t ha...,NaN,Dreamliner,Business,Business Class,...,0.654033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
24353,24353,ZIPAIR,"""lost all of our money with no refund""",20th May 2022,True,They lied about connection in Narita and we ...,NaN,NaN,Solo Leisure,Economy Class,...,0.929426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

#### Check corrected

In [79]:
df_corrected_overallrating10[df_corrected_overallrating10['Overall_Rating'] == '10']

,RowId,Airline Name,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,Seat Type,...,sentiment_score,img_resnet50_score,img_resnet50_label,img_blip_caption,img_clip_embedding,img_caption_clip_embedding,img_resnet50label_clip_embedding,img_vs_caption_similarity,img_caption_vs_resnetlabel_similarity,Overall_Rating
15,15,Adria Airways,"""Flight was very comfortable""",4th May 2018,True,Frankfurt to Ljubljana. Flight was very comf...,NaN,NaN,Business,Economy Class,...,0.873290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
23,23,Adria Airways,"""nice and comfortable flights""",10th November 2016,False,Two very short flights with Adria Airways fr...,NaN,CRJ900,Business,Economy Class,...,0.931223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
31,31,Adria Airways,"""Clean and fresh aircraft """,29th July 2016,False,Tallinn to Stockholm with Adria Airways. Cle...,NaN,Canadair 700,Solo Leisure,Economy Class,...,0.908528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
33,33,Adria Airways,"""nice and professional service""",11th July 2016,False,Two short flights with Adria Airways (Ljublj...,NaN,CRJ900,Solo Leisure,Economy Class,...,0.924249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
41,41,Adria Airways,"""staff friendly but unobtrusive""",2nd September 2015,False,Excellent flights both ways with Adria Airways...,NaN,A319,Family Leisure,Economy Class,...,0.960242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24325,24325,ZIPAIR,"""I recommend ZIPAIR""",6th March 2023,False,I recommend ZIPAIR. My friend and I booked a...,NaN,NaN,Solo Leisure,Economy Class,...,0.745333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
24327,24327,ZIPAIR,"""Excellent experience with ZIPAIR""",28th February 2023,True,"Excellent experience with ZIPAIR, from quick...",NaN,NaN,Couple Leisure,Economy Class,...,0.943604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
24328,24328,ZIPAIR,"""Excellent flight""",7th February 2023,True,Excellent flight. Almost empty flight. Had t...,https://www.airlinequality.com/wp-content/uplo...,Boeing 787,Couple Leisure,Economy Class,...,0.846643,8.587234,airliner,the interior of an airplane with people sittin...,"tensor([[-2.5044e-02, 2.4928e-02, -1.5578e-02...","tensor([[ 3.1944e-02, -6.4164e-04, -1.5116e-02...","tensor([[ 3.2589e-03, 1.9619e-02, -9.0548e-03...",0.296376,0.691259,10
24329,24329,ZIPAIR,"""business class seats were incredibly reasonable""",1st February 2023,True,We chose Zipair because the business class se...,NaN,NaN,Couple Leisure,Business Class,...,0.954740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
24334,24334,ZIPAIR,"""I cannot say enough good things about Zipair""",21st November 2022,False,I cannot say enough good things about Zipair...,NaN,Boeing 787-8,Couple Leisure,Business Class,...,0.950348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10

#### Persist to CSV file

In [82]:
df_corrected_overallrating10\
    .to_csv("data/silver_20250322_Airline_Reviews_Corrected_WithSentimentImageLabels.csv", index=False)