In [1]:
import pandas as pd

In [4]:
df_20250322 = pd.read_csv('data/bronze_20250322_Airline_Reviews_withImageUrls.csv')
df_20250322

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,...,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,https://www.airlinequality.com/wp-content/uplo...,NaN,Solo Leisure,...,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,NaN,E120,Solo Leisure,...,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,NaN,Embraer E120,Solo Leisure,...,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,NaN,Solo Leisure,...,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,NaN,Couple Leisure,...,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24349,24349,ZIPAIR,1,"""customer service is terrible""",5th July 2022,False,Bangkok to Tokyo. I’ve flown many low cost ai...,NaN,NaN,Couple Leisure,...,Bangkok to Tokyo,June 2022,2.0,1.0,NaN,1.0,1.0,1.0,1.0,no
24350,24350,ZIPAIR,1,"""Avoid at all costs""",1st June 2022,True,Avoid at all costs. I booked flights to go f...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,June 2022,NaN,NaN,NaN,NaN,NaN,NaN,1.0,no
24351,24351,ZIPAIR,3,"""Will not recommend to anyone""",31st May 2022,True,Flight was leaving at 23.15 and after an hou...,NaN,NaN,Business,...,Bangkok to Tokyo,May 2022,2.0,4.0,2.0,1.0,NaN,NaN,2.0,no
24352,24352,ZIPAIR,6,"""It was immaculately clean""",23rd May 2022,True,Zipair is JAL’s budget airline. They don’t ha...,NaN,Dreamliner,Business,...,Tokyo to Los Angeles,May 2022,3.0,4.0,3.0,1.0,2.0,5.0,5.0,yes
24353,24353,ZIPAIR,1,"""lost all of our money with no refund""",20th May 2022,True,They lied about connection in Narita and we ...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,May 2022,NaN,NaN,NaN,1.0,NaN,NaN,1.0,no

In [50]:
df_20250322['Review Date'] = df_20250322['Review Date'].str.replace('th','')
df_20250322['Review Date'] = df_20250322['Review Date'].str.replace('st','')
df_20250322['Review Date'] = df_20250322['Review Date'].str.replace('rd','')
df_20250322['Review Date'] = df_20250322['Review Date'].str.replace('Augu','August')

In [52]:
df_20250322['Review Date']

0         11 November 2019
1             25 June 2019
2             25 June 2019
3        28 September 2019
4        24 September 2019
               ...
24349          5 July 2022
24350          1 June 2022
24351          31 May 2022
24352          23 May 2022
24353          20 May 2022
Name: Review Date, Length: 24354, dtype: object

In [56]:
df_20250322['Review Date'] = pd.to_datetime(df_20250322['Review Date'], format='mixed')

In [58]:
df_20250322

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,...,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,0,AB Aviation,9,"""pretty decent airline""",2019-11-11,True,Moroni to Moheli. Turned out to be a pretty ...,https://www.airlinequality.com/wp-content/uplo...,NaN,Solo Leisure,...,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,1,AB Aviation,1,"""Not a good airline""",2019-06-25,True,Moroni to Anjouan. It is a very small airline...,NaN,E120,Solo Leisure,...,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,2,AB Aviation,1,"""flight was fortunately short""",2019-06-25,True,Anjouan to Dzaoudzi. A very small airline an...,NaN,Embraer E120,Solo Leisure,...,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,3,Adria Airways,1,"""I will never fly again with Adria""",2019-09-28,False,Please do a favor yourself and do not fly wi...,NaN,NaN,Solo Leisure,...,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,4,Adria Airways,1,"""it ruined our last days of holidays""",2019-09-24,True,Do not book a flight with this airline! My fr...,NaN,NaN,Couple Leisure,...,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24349,24349,ZIPAIR,1,"""customer service is terrible""",2022-07-05,False,Bangkok to Tokyo. I’ve flown many low cost ai...,NaN,NaN,Couple Leisure,...,Bangkok to Tokyo,June 2022,2.0,1.0,NaN,1.0,1.0,1.0,1.0,no
24350,24350,ZIPAIR,1,"""Avoid at all costs""",2022-06-01,True,Avoid at all costs. I booked flights to go f...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,June 2022,NaN,NaN,NaN,NaN,NaN,NaN,1.0,no
24351,24351,ZIPAIR,3,"""Will not recommend to anyone""",2022-05-31,True,Flight was leaving at 23.15 and after an hou...,NaN,NaN,Business,...,Bangkok to Tokyo,May 2022,2.0,4.0,2.0,1.0,NaN,NaN,2.0,no
24352,24352,ZIPAIR,6,"""It was immaculately clean""",2022-05-23,True,Zipair is JAL’s budget airline. They don’t ha...,NaN,Dreamliner,Business,...,Tokyo to Los Angeles,May 2022,3.0,4.0,3.0,1.0,2.0,5.0,5.0,yes
24353,24353,ZIPAIR,1,"""lost all of our money with no refund""",2022-05-20,True,They lied about connection in Narita and we ...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,May 2022,NaN,NaN,NaN,1.0,NaN,NaN,1.0,no

In [6]:
df_20250324 = pd.read_csv('data/bronze_20250324_Airline_Reviews_withImageUrls.csv')
df_20250324

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,...,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,https://www.airlinequality.com/wp-content/uplo...,NaN,Solo Leisure,...,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,NaN,E120,Solo Leisure,...,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,NaN,Embraer E120,Solo Leisure,...,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,NaN,Solo Leisure,...,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,NaN,Couple Leisure,...,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24349,24349,ZIPAIR,1,"""customer service is terrible""",5th July 2022,False,Bangkok to Tokyo. I’ve flown many low cost ai...,NaN,NaN,Couple Leisure,...,Bangkok to Tokyo,June 2022,2.0,1.0,NaN,1.0,1.0,1.0,1.0,no
24350,24350,ZIPAIR,1,"""Avoid at all costs""",1st June 2022,True,Avoid at all costs. I booked flights to go f...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,June 2022,NaN,NaN,NaN,NaN,NaN,NaN,1.0,no
24351,24351,ZIPAIR,3,"""Will not recommend to anyone""",31st May 2022,True,Flight was leaving at 23.15 and after an hou...,NaN,NaN,Business,...,Bangkok to Tokyo,May 2022,2.0,4.0,2.0,1.0,NaN,NaN,2.0,no
24352,24352,ZIPAIR,6,"""It was immaculately clean""",23rd May 2022,True,Zipair is JAL’s budget airline. They don’t ha...,NaN,Dreamliner,Business,...,Tokyo to Los Angeles,May 2022,3.0,4.0,3.0,1.0,2.0,5.0,5.0,yes
24353,24353,ZIPAIR,1,"""lost all of our money with no refund""",20th May 2022,True,They lied about connection in Narita and we ...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,May 2022,NaN,NaN,NaN,1.0,NaN,NaN,1.0,no

In [60]:
df_20250324['Review Date'] = df_20250324['Review Date'].str.replace('th','')
df_20250324['Review Date'] = df_20250324['Review Date'].str.replace('st','')
df_20250324['Review Date'] = df_20250324['Review Date'].str.replace('rd','')
df_20250324['Review Date'] = df_20250324['Review Date'].str.replace('Augu','August')

In [64]:
df_20250324['Review Date']

0         11 November 2019
1             25 June 2019
2             25 June 2019
3        28 September 2019
4        24 September 2019
               ...
24349          5 July 2022
24350          1 June 2022
24351          31 May 2022
24352          23 May 2022
24353          20 May 2022
Name: Review Date, Length: 24354, dtype: object

In [66]:
df_20250324['Review Date'] = pd.to_datetime(df_20250324['Review Date'], format='mixed')

In [68]:
df_20250324

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,...,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,0,AB Aviation,9,"""pretty decent airline""",2019-11-11,True,Moroni to Moheli. Turned out to be a pretty ...,https://www.airlinequality.com/wp-content/uplo...,NaN,Solo Leisure,...,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,1,AB Aviation,1,"""Not a good airline""",2019-06-25,True,Moroni to Anjouan. It is a very small airline...,NaN,E120,Solo Leisure,...,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,2,AB Aviation,1,"""flight was fortunately short""",2019-06-25,True,Anjouan to Dzaoudzi. A very small airline an...,NaN,Embraer E120,Solo Leisure,...,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,3,Adria Airways,1,"""I will never fly again with Adria""",2019-09-28,False,Please do a favor yourself and do not fly wi...,NaN,NaN,Solo Leisure,...,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,4,Adria Airways,1,"""it ruined our last days of holidays""",2019-09-24,True,Do not book a flight with this airline! My fr...,NaN,NaN,Couple Leisure,...,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24349,24349,ZIPAIR,1,"""customer service is terrible""",2022-07-05,False,Bangkok to Tokyo. I’ve flown many low cost ai...,NaN,NaN,Couple Leisure,...,Bangkok to Tokyo,June 2022,2.0,1.0,NaN,1.0,1.0,1.0,1.0,no
24350,24350,ZIPAIR,1,"""Avoid at all costs""",2022-06-01,True,Avoid at all costs. I booked flights to go f...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,June 2022,NaN,NaN,NaN,NaN,NaN,NaN,1.0,no
24351,24351,ZIPAIR,3,"""Will not recommend to anyone""",2022-05-31,True,Flight was leaving at 23.15 and after an hou...,NaN,NaN,Business,...,Bangkok to Tokyo,May 2022,2.0,4.0,2.0,1.0,NaN,NaN,2.0,no
24352,24352,ZIPAIR,6,"""It was immaculately clean""",2022-05-23,True,Zipair is JAL’s budget airline. They don’t ha...,NaN,Dreamliner,Business,...,Tokyo to Los Angeles,May 2022,3.0,4.0,3.0,1.0,2.0,5.0,5.0,yes
24353,24353,ZIPAIR,1,"""lost all of our money with no refund""",2022-05-20,True,They lied about connection in Narita and we ...,NaN,NaN,Solo Leisure,...,Singapore to Tokyo,May 2022,NaN,NaN,NaN,1.0,NaN,NaN,1.0,no

In [78]:
df_20250322_grouped = df_20250322.groupby(['Airline Name']).agg(review_count=('Airline Name', 'count'), max_review_date=('Review Date', 'max'))\
    .sort_values(by='review_count', ascending=False)
df_20250322_grouped

                           review_count max_review_date
Airline Name
Jetstar Pacific                     100      2024-02-29
Jetblue Airways                     100      2025-03-17
Go First                            100      2023-05-02
GoAir                               100      2021-11-26
Gulf Air                            100      2025-03-10
...                                 ...             ...
Ariana Afghan Airlines                1      2015-09-03
Pan Pacific Airlines                  1      2019-12-30
FlyGabon                              1      2025-02-18
Novair                                1      2011-03-21
JC International Airlines             1      2019-12-25

[518 rows x 2 columns]

In [74]:
df_20250324_grouped = df_20250324.groupby(['Airline Name']).agg(review_count=('Airline Name', 'count'), max_review_date=('Review Date', 'max'))\
    .sort_values(by='review_count', ascending=False)
df_20250324_grouped

                           review_count max_review_date
Airline Name
Jetstar Pacific                     100      2024-02-29
Jetblue Airways                     100      2025-03-17
Go First                            100      2023-05-02
GoAir                               100      2021-11-26
Gulf Air                            100      2025-03-10
...                                 ...             ...
Ariana Afghan Airlines                1      2015-09-03
Pan Pacific Airlines                  1      2019-12-30
FlyGabon                              1      2025-02-18
Novair                                1      2011-03-21
JC International Airlines             1      2019-12-25

[518 rows x 2 columns]

In [98]:
df_20250324_22_merged = df_20250324_grouped.merge(df_20250322_grouped, how='left', on=['Airline Name'], suffixes=('_0324', '_0322'))

In [100]:
df_20250324_22_merged[df_20250324_22_merged['max_review_date_0324'] != df_20250324_22_merged['max_review_date_0322']]

,review_count_0324,max_review_date_0324,review_count_0322,max_review_date_0322
Airline Name,,,,
Frontier Airlines,100,2025-03-24,100,2025-03-11
Breeze Airways,100,2025-03-24,100,2025-03-21
Cebu Pacific,100,2025-03-23,100,2025-02-17
French Bee,100,2025-03-22,100,2025-01-14
TAP Portugal,100,2025-03-24,100,2025-03-03
Thai AirAsia,100,2025-03-24,100,2024-12-26
Turkish Airlines,100,2025-03-24,100,2025-03-14
VivaAerobús,100,2025-03-24,100,2025-01-22
Volotea,100,2025-03-24,100,2025-03-22
Wizz Air,100,2025-03-23,100,2025-03-20
Porter Airlines,100,2025-03-24,100,2025-03-17
Scoot,100,2025-03-23,100,2025-03-20
flydubai,100,2025-03-24,100,2025-02-19
AirAsia X,100,2025-03-24,100,2025-02-02
Air India Express,100,2025-03-23,100,2025-03-16
American Airlines,100,2025-03-23,100,2025-03-21

In [94]:
df_20250322[df_20250322['Airline Name'] == 'Frontier Airlines']

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,...,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
10634,10634,Frontier Airlines,2,"""turned into a nightmare""",2025-03-11,True,I was in good spirits getting ready to retu...,NaN,A321 Neo,Solo Leisure,...,San Juan to New York,March 2025,2.0,2.0,1.0,1.0,1.0,1.0,2.0,no
10635,10635,Frontier Airlines,1,"""Worst airline ever""",2025-03-10,True,Worst airline ever. 4 hours delay which we ...,NaN,NaN,Couple Leisure,...,Ft. Lauderdale to Philadelphia,March 2025,1.0,2.0,NaN,2.0,NaN,NaN,1.0,no
10636,10636,Frontier Airlines,1,"""The worst experience""",2025-03-09,True,I’m a frequent flyer and was forced to fly ...,NaN,NaN,Couple Leisure,...,Omaha to Las Vegas,March 2025,1.0,2.0,NaN,1.0,NaN,1.0,1.0,no
10637,10637,Frontier Airlines,1,"""had to pay for my bag again""",2025-03-08,False,I flew from Orlando to Ponce. I had paid for...,NaN,NaN,Family Leisure,...,Orlando to Ponce,February 2025,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
10638,10638,Frontier Airlines,1,“flight cancelled without my knowledge”,2025-03-07,True,My flight was cancelled without my knowledge ...,NaN,NaN,Solo Leisure,...,Dallas to Fargo,March 2025,1.0,1.0,1.0,1.0,NaN,NaN,1.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10729,10729,Frontier Airlines,1,"""extremely dissatisfied with the service""",2024-08-21,False,"On July 29, 2024, at 1:02 PM, I purchased fo...",NaN,NaN,Family Leisure,...,Baltimore Washington to Chicago,August 2024,2.0,NaN,NaN,1.0,NaN,NaN,1.0,no
10730,10730,Frontier Airlines,1,“this airline will leave you stranded”,2024-08-20,False,"This is the worst airline ever, please don't ...",NaN,NaN,Couple Leisure,...,Atlanta to Orlando,August 2024,1.0,1.0,NaN,2.0,NaN,NaN,1.0,no
10731,10731,Frontier Airlines,1,"""deliberately gives false information""",2024-08-19,True,Frontier deliberately gives false informati...,NaN,NaN,Couple Leisure,...,Orlando to Atlanta,August 2024,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
10732,10732,Frontier Airlines,1,"""worst customer experiences""",2024-08-18,False,I am in Business Consulting and I have rarel...,NaN,A320,Family Leisure,...,Denver to Chicago,August 2024,3.0,1.0,NaN,1.0,1.0,NaN,1.0,no
10733,10733,Frontier Airlines,1,"""they extort money from you""",2024-08-14,True,"I knew Frontier was a no frills, fees happy...",NaN,NaN,Couple Leisure,...,Seattle to Denver,August 2024,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no

In [96]:
df_20250324[df_20250324['Airline Name'] == 'Frontier Airlines']

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Top Review Image Url,Aircraft,Type Of Traveller,...,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
10634,10634,Frontier Airlines,1,“Choose anyone but Frontier”,2025-03-24,True,"It's been many, many years since I've been en...",NaN,NaN,Couple Leisure,...,Tampa to Boston,March 2025,1.0,2.0,NaN,1.0,NaN,NaN,1.0,no
10635,10635,Frontier Airlines,1,“Their policies are inhuman”,2025-03-23,True,I had a horrible experience in the Orlando ai...,NaN,A320,Family Leisure,...,Orlando to Denver,March 2025,1.0,3.0,NaN,1.0,NaN,NaN,1.0,no
10636,10636,Frontier Airlines,1,"""the worst airline ever""",2025-03-22,False,Frontier is the worst airline ever. 6 years ...,NaN,NaN,Family Leisure,...,Los Angeles to Salt Lake City,March 2025,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
10637,10637,Frontier Airlines,2,"""turned into a nightmare""",2025-03-11,True,I was in good spirits getting ready to retu...,NaN,A321 Neo,Solo Leisure,...,San Juan to New York,March 2025,2.0,2.0,1.0,1.0,1.0,1.0,2.0,no
10638,10638,Frontier Airlines,1,"""Worst airline ever""",2025-03-10,True,Worst airline ever. 4 hours delay which we ...,NaN,NaN,Couple Leisure,...,Ft. Lauderdale to Philadelphia,March 2025,1.0,2.0,NaN,2.0,NaN,NaN,1.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10729,10729,Frontier Airlines,2,“Total bait and switch”,2024-08-27,False,I booked a direct flight on Frontier's websit...,NaN,NaN,Family Leisure,...,Salt Lake City to San Fransico,August 2024,3.0,3.0,NaN,3.0,NaN,NaN,3.0,no
10730,10730,Frontier Airlines,1,"“No voucher, no reimbursement, no apology”",2024-08-22,True,Was at initial gate (T17) at 3PM waiting. At ...,NaN,NaN,Solo Leisure,...,Atlanta to Chicago,August 2024,2.0,3.0,1.0,2.0,NaN,NaN,1.0,no
10731,10731,Frontier Airlines,3,"""definitely do not recommend them""",2024-08-21,True,Frontier moved my return flight to two days...,NaN,NaN,Solo Leisure,...,Buffalo to Orlando,August 2024,4.0,3.0,1.0,2.0,NaN,NaN,2.0,no
10732,10732,Frontier Airlines,1,"""extremely dissatisfied with the service""",2024-08-21,False,"On July 29, 2024, at 1:02 PM, I purchased fo...",NaN,NaN,Family Leisure,...,Baltimore Washington to Chicago,August 2024,2.0,NaN,NaN,1.0,NaN,NaN,1.0,no
10733,10733,Frontier Airlines,1,“this airline will leave you stranded”,2024-08-20,False,"This is the worst airline ever, please don't ...",NaN,NaN,Couple Leisure,...,Atlanta to Orlando,August 2024,1.0,1.0,NaN,2.0,NaN,NaN,1.0,no